services:
  # Backend Flask API
  - type: web
    name: reddit-crawler-api
    env: python
    region: singapore
    plan: free
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn app:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: client_id
        sync: false
      - key: client_secret
        sync: false
      - key: user_agent
        sync: false
      - key: telegram_token
        sync: false
      - key: mongo_uri
        fromDatabase:
          name: reddit-crawler-db
          property: connectionString

  # Frontend React app
  - type: web
    name: reddit-crawler-frontend
    env: static
    region: singapore
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: reddit-crawler-api
          type: web
          property: url

databases:
  # MongoDB database
  - name: reddit-crawler-db
    plan: free
    type: mongodb
    region: singapore
